// src/components/Home.jsx
import React from 'react'

const Home = () => {
  return (
    <section className="section hero">
      <h1 className="hero-name">Dinesh Sinnathamby</h1>
      <p className="hero-title">Student Developer</p>
      <p>w alfred cen</p>
      <p>w alfred cen</p>
      <p>w roy lu</p>
      <p>w richard liu</p>
      <p>w justin tian</p>
      <p>w anson xiao</p>
      <p>w jackson lin</p>
      <p>w justin cao</p>
      <p>w leo fang</p>
      <p>w everyone else who voted bro</p>
      <p>w bryan</p>
      <p>w oscar</p>
    </section>
    
  )
}

export default Home

// src/components/Home.svelte
<section class="section hero">
  <h1 class="hero-name">Dinesh Sinnathamby</h1>
  <p class="hero-title">Student Developer</p>
  <p>w alfred cen</p>
  <p>w alfred cen</p>
  <p>w roy lu</p>
  <p>w richard liu</p>
  <p>w justin tian</p>
  <p>w anson xiao</p>
  <p>w jackson lin</p>
  <p>w justin cao</p>
  <p>w leo fang</p>
  <p>w everyone else who voted bro</p>
  <p>w bryan</p>
  <p>w oscar</p>
</section>
