// src/components/Navbar.svelte
<script lang="ts">
  import { link } from "svelte-spa-router";
</script>

<nav class="navbar">
  <div class="nav-content">
    <a href="/" use:link class="nav-link">Home</a>
    <a href="/showcase" use:link class="nav-link">Showcase</a>
    <a href="/achievements" use:link class="nav-link">Certifications</a>
    <a href="/contact" use:link class="nav-link">Contact</a>
  </div>
</nav>

// src/components/Navbar.tsx
import { Link } from 'react-router-dom'

function Navbar() {
  return (
    <nav className="navbar">
      <div className="nav-content">
        <Link to="/" className="nav-link">Home</Link>
        <Link to="/showcase" className="nav-link">Showcase</Link>
        <Link to="/achievements" className="nav-link">Certifications</Link>
        <Link to="/contact" className="nav-link">Contact</Link>
      </div>
    </nav>
  )
}

export default Navbar
