// src/App.tsx
import { Routes, Route, useLocation } from 'react-router-dom'
import { useEffect } from 'react'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Home from './components/Home'
import Showcase from './components/Showcase'
import Achievements from './components/Achievements'
import Contact from './components/Contact'

function App() {
  const location = useLocation()

  // Scroll to top on route change
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [location])

  return (
    <div className="portfolio">
      <Navbar />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/showcase" element={<Showcase />} />
        <Route path="/achievements" element={<Achievements />} />
        <Route path="/contact" element={<Contact />} />
      </Routes>
      <Footer />
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import { location } from "svelte-spa-router";
  
  import Navbar from "./components/Navbar.svelte";
  import Footer from "./components/Footer.svelte";
  import Home from "./components/Home.svelte";
  import Showcase from "./components/Showcase.svelte";
  import Achievements from "./components/Achievements.svelte";
  import Contact from "./components/Contact.svelte";

  const routes = {
    '/': Home,
    '/showcase': Showcase,
    '/achievements': Achievements,
    '/contact': Contact,
  };

  // Scroll to top on route change
  $: if ($location) {
    window.scrollTo(0, 0);
  }
</script>

<div class="portfolio">
  <Navbar />
  <Router {routes} />
  <Footer />
</div>
