// src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import { location } from "svelte-spa-router";
  
  import Navbar from "./components/Navbar.svelte";
  import Footer from "./components/Footer.svelte";
  import Home from "./components/Home.svelte";
  import Showcase from "./components/Showcase.svelte";
  import Achievements from "./components/Achievements.svelte";
  import Contact from "./components/Contact.svelte";

  const routes = {
    '/': Home,
    '/showcase': Showcase,
    '/achievements': Achievements,
    '/contact': Contact,
  };

  // Scroll to top on route change
  $: if ($location) {
    window.scrollTo(0, 0);
  }
</script>

<div class="portfolio">
  <Navbar />
  <Router {routes} />
  <Footer />
</div>

// src/App.jsx
import { Routes, Route, useLocation } from "react-router-dom";
import { useEffect } from "react";

import Navbar from "./components/Navbar.jsx";
import Footer from "./components/Footer.jsx";
import Home from "./components/Home.jsx";
import Showcase from "./components/Showcase.jsx";
import Achievements from "./components/Achievements.jsx";
import Contact from "./components/Contact.jsx";

function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}

function App() {
  return (
    <div className="portfolio">
      <ScrollToTop />
      <Navbar />

      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/showcase" element={<Showcase />} />
        <Route path="/achievements" element={<Achievements />} />
        <Route path="/contact" element={<Contact />} />
      </Routes>

      <Footer />
    </div>
  );
}

export default App;
